### ISSUE TITLE
A question in the processing script of h36m~~~

### ISSUE THREAD

**Issue by 1165048017** [isarandi/metrabs#12]
The code from 75-77 in `extract_frames_and_boxes_h36m.py` may have mistake?
```
if not is_image_readable(dst_path):
      print(dst_path)
      imageio.imwrite(dst_path, frame, quality=95)
```
The function description is `Save every 5th and 64th frame from a video as images.` 
Maybe the `not is_image_readable` should change to be `is_image_readable`?

**Comment by isarandi** [comment]
That line checks if the image has already been generated. If there is a readable image already at the destination path then we don't need to save it again. I could have removed this part, it's only relevant if the process breaks down and needs to be started again.

**Comment by 1165048017** [comment]
> That line checks if the image has already been generated. If there is a readable image already at the destination path then we don't need to save it again. I could have removed this part, it's only relevant if the process breaks down and needs to be started again.

Oh, my misunderstanding ^_^ Thanks for your good job
