### ISSUE TITLE
Coarse-to-fine volumetric prediction for single-image 3D human pose: Supplementary material

### ISSUE THREAD

**Issue by zhLawliet** [isarandi/metrabs#17]
hi, can you provide the paper  [55]"Coarse-to-fine volumetric prediction for single-image 3D human pose: Supplementary material", which i can't find on the web, thanks

**Comment by isarandi** [comment]
You can find it from the website of Georgios Pavlakos at https://geopavlakos.github.io/projects/volumetric/files/volumetric-supp.pdf

**Comment by zhLawliet** [comment]
thanks
