### ISSUE TITLE
Dataset with different set and sequence of keypoints

### ISSUE THREAD

**Issue by nikhilchh** [isarandi/metrabs#19]
MPII has 16 keypoints and COCO 17 keypoints. Out of them 12 are common. And also they are indexed differently.
And you have used so many different datasets.

So my questions are:
1- How do you handle different datasets ?
2- Does most of the datasets provide 12 2d keypoints for shoulders, elbows, wrists, hips, knees and ankle ?
3-Is it very important to take care of subtle differences in the way different datasets label a certain keypoint ? Like shoulder from COCO might be a little OFF compared to shoulder from MPII ?

My approach to question 1 is as follows:
1- Create json file for every dataset in coco format and only consider 12 keypoints which are common with most of the datasets. (pairs of shoulders, elbows, wrists, hips, knees, ankles.). Create extra keypoints like neck and head-center at this stage. Neck head-center keypoint creation code will be specific to every dataset. Now we will have a standard json file for every dataset with 14 keypoints.
2- Rest of code like data loading, data transformations stays generic.
3- Network output will be fixed (say 14 heatmaps and 28 PAFs) 
Would like to get your opinion and tips as you have already handled a lot of datasets. 

PS: I am currently focusing of 2d keypoints.

**Comment by isarandi** [comment]
It's certainly an annoyance to deal with the different skeleton conventions. I think in the long term the best strategy would be to map everything onto one human body model such as SMPL or STAR. Somewhat similar to how AMASS was constructed using MoSh.

In this case I regressed some linear mappings, somewhat similar to the joint regressor in SMPL.

As for whether differences such as COCO shoulder vs MPII shoulder matter or not, I have no quantitative data to really answer this. You'd have to evaluate it. I would say it's more of an issue with the hips, which are sometimes defined at the outer body surface, sometimes at the upper, rotational joint of the thigh bone inside the body.

I hope this helps.

**Comment by personal-coding** [comment]
> In this case I regressed some linear mappings, somewhat similar to the joint regressor in SMPL.

Are you able to share the linear mappings? I created my own, but having the mapping would ensure my SMPL locations are consistent with the prediction locations.
