### ISSUE TITLE
running colab with own person boxes

### ISSUE THREAD

**Issue by nikky4D** [isarandi/metrabs#2]
Hi,

I am using the colab to run pose estimation on images, for 2d pose estimation. For an input image, I would like to pass in person boxes, and the image, without having to pass any intrinsics. I have tried the two models: multiperson_smpl, and multiperson_smpl_combined. However, both don't allow me to pass in just the two inputs : image and person-boxes. 

Can you direct me to a model/function that can do that?

**Comment by isarandi** [comment]
Hello,

If you don't have a calibrated intrinsic matrix, the absolute distance estimation task will necessarily be highly underspecified.

Nevertheless, if you have no calibration, the best alternative is to guess the field of view, which is roughly around 50-60 degrees for the larger image side in unzoomed consumer (smartphone) cameras. The root-relative poses and the depth order between people should be mostly unaffected by a roughly okay approximation.

You can create such a guessed intrinsic matrix as follows:

```python
field_of_view_degrees = 50
imshape = tf.cast(tf.shape(image)[1:3], tf.float32)
focal_length = (
        tf.reduce_max(imshape) /
        tf.constant(np.tan(np.deg2rad(field_of_view_degrees) / 2) * 2, tf.float32))
intrinsics = tf.convert_to_tensor(
    [[[focal_length, 0, imshape[1] / 2],
      [0, focal_length, imshape[0] / 2],
      [0, 0, 1]]], tf.float32)
```

Let me know if it works or you have any further issues.

**Comment by stncil** [comment]
hi @isarandi , thank you for addressing all the issues here.
Could let me know what you mean by "larger image side" in **larger image side in unzoomed consumer (smartphone) cameras** stated above in your answer?

**Comment by isarandi** [comment]
It just means max(height, width), ie height for portrait and width for landscape orientation.
