### ISSUE TITLE
Can you do it in real time

### ISSUE THREAD

**Issue by zhanghongyong123456** [isarandi/metrabs#20]
Can you capture the action in real time

**Comment by StefanoBerti** [comment]
The metrabs_mob3l_y4t model is very fast on any GPU device, while the metrabs_eff2l_y4 does about 4 fps in a GeForce RTX 2080 and uses about 8 GBs of VRAM, but can deal much better with occlusions and truncations

**Comment by isarandi** [comment]
You can check some timing measurements on this poster: https://istvansarandi.com/media/sarandi-eccv2022-demo-poster.pdf

It can run in real time even on a laptop GPU.
