### ISSUE TITLE
no build yet, install_dependencies.sh stalls on linux

### ISSUE THREAD

**Issue by bjornmose** [isarandi/metrabs#21]
I'd really like to see it working bit failed to build on linux yet.
Starting off clean with

~/Documents/metrabs$ ./install_dependencies.sh 

.............................

gcc -pthread -B /home/jenscave/miniconda3/envs/metrabs/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/jenscave/miniconda3/envs/metrabs/lib/python3.8/site-packages/numpy/core/include -I../common -I/home/jenscave/miniconda3/envs/metrabs/include/python3.8 -c pycocotools/_mask.c -o build/temp.linux-x86_64-3.8/pycocotools/_mask.o -Wno-cpp -Wno-unused-function -std=c99
gcc: error: pycocotools/_mask.c: No such file or directory
error: command 'gcc' failed with exit status 1
make: *** [Makefile:3: all] Error 1
__

**Comment by isarandi** [comment]
Thanks for reporting the issue! In fact, this was because I erroneously removed the Cython dependency (because I forgot why it was needed). Now I added it back in `install_dependencies.sh`.

Please try it now. If it still doesn't work, feel free to reopen the issue.

**Comment by isarandi** [comment]
Just to be sure: Note that setting up these dependencies is only required if you'd like to _train_ the model.
