### ISSUE TITLE
poseviz error

### ISSUE THREAD

**Issue by skyhe1410** [isarandi/metrabs#23]
show nothing except camera

**Comment by skyhe1410** [comment]
run PoseViz demo.py, no ground plane.

**Comment by isarandi** [comment]
This is probably a problem with your Mayavi installation, VTK, Qt etc. It can be tricky to get it all right. For me, only the conda installation worked under Ubuntu 18.04. This may be different under other OSs.

Please check out the [Mayavi installation docs](https://docs.enthought.com/mayavi/mayavi/installation.html), and the open issues in the [Mayavi GitHub repo](https://github.com/enthought/mayavi/issues).
