### ISSUE TITLE
The demo problem

### ISSUE THREAD

**Issue by LeeHY-1** [isarandi/metrabs#27]
Hello, I tried to run the demo.py, but the output is as follows：
>The X11 connection broke: No error (code 0)
      XIO:  fatal IO error 22 (Invalid argument) on X server "localhost:10.0"
      after 400 requests (400 known processed) with 0 events remaining.

And I found it happened after this line:
`viz = poseviz.PoseViz(joint_names, joint_edges)`

How to solve it?
My operating system is Ubuntu 18.04.5 LTS.

**Comment by isarandi** [comment]
This is unlikely to be specific about code in this repo.
