### ISSUE TITLE
No tracking reasoning of hand joint

### ISSUE THREAD

**Issue by psiydown** [isarandi/metrabs#29]
First I would like to say great work.The hand or palm joint follows the wrist and has no self motion tracking, Are there any options or modifications that can be turned on?
Is there any plan for an accelerated version based on TensorRT? Thank you!

**Comment by isarandi** [comment]
Hi, this is a known limitation that comes from the training data. Specifically, the SMPL joints are learned from the SURREAL dataset, which is a synthetic dataset that does not articulate the hand joint compared to the wrist. This may be updated in the future using a suitable dataset, but I'm not sure when I'll have time to experiment with that.

TensorRT: unfortunately I won't have time to do this on the short term, but some other users have experimented with it, check out those Github issues, perhaps you find something useful there.
