### ISSUE TITLE
no run_person_detector_3dhp.sh scripts

### ISSUE THREAD

**Issue by ghost** [isarandi/metrabs#3]
Hello, Mr.Sarandi.
I am an undergraduate student in Korea.
I would like to use your MeTRAbs because it seems to be the best 3d pose reconstruction method.

I want to train 3dhp data set. 
However, the run_person_detector_3dhp.sh script file required for training has not been uploaded, 

So I downloaded the darknet you uploaded and entered the following command.
darknet/run_yolo.sh --image-paths-file 3dhp_images_for_detection.txt --out-path "$DATA_ROOT/3dhp/yolov3_person_detections.pkl"
However, there was no --image-paths-file arguments, but only --image-root.

I think that after you uploaded the darknet repository, 
you added the --image-paths-file contents separately.

I want to train with 3dhp data, but I can't do more because the command is blocked.
Could you check it for me?

Thanks

**Comment by isarandi** [comment]
Thank you for your interest and for letting me know about this mismatch. I added the `--image-paths-file` to the darknet fork repo.
