### ISSUE TITLE
About the predicted skeleton and bone length

### ISSUE THREAD

**Issue by minhnhatvt** [isarandi/metrabs#35]
Hi, thank you for the excellent work. I would like to ask some questions:

1. I've run metrabs on some videos and noticed that the resulted skeletons have identical bone lengths across different people. Could you explain more about the processing (e.g. is there any post-processing or normalization step of the resulted skeleton?) 
2. I run the model on my video using `demo_video_batched.py` (metrabs_eff2l_y4, batch size=16, and the image size is 1920x1080) but the program crashed after predicting roughly 2000 frames. Maybe there exists some memory leak inside the detector? (My specs is Nvidia 2080Ti 11GB with 48GB of RAM)

**Comment by vladmandic** [comment]
regarding crash during very long job, i find that tuning a bit Cuda does help  
plus it makes it simple to monitor gpu memory since allocation is on request instead of preallocate all  
(cuda allocated memory still never gets deallocated until cuda exits to avoid memory fragmentation)

```python
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2' # reduce tf logging
os.environ['CUDA_CACHE_DISABLE'] = '0'
os.environ['TF_FORCE_GPU_ALLOW_GROWTH'] = 'true'
os.environ['TF_GPU_THREAD_MODE'] = 'gpu_private'
os.environ['TF_USE_CUDNN_BATCHNORM_SPATIAL_PERSISTENT'] = '1'
os.environ['TF_NEED_HDFS'] = '0'
os.environ['TF_NEED_GCP'] = '0'
os.environ['TF_CUDA_COMPUTE_CAPABILITIES'] = '8.0,8.6'
os.environ['TF_ENABLE_XLA 1'] = '1'
```
