### ISSUE TITLE
Meaning of Z

### ISSUE THREAD

**Issue by funnypig521** [isarandi/metrabs#37]
Excuse me.When I ran the demo, I found that the Z value was negative. What does this mean?
Can absolute depth be negative?

**Comment by isarandi** [comment]
Z is the depth, the distance along the optical axis of the camera. It's not impossible that this may be negative in certain exceptional cases, like a person standing very close to the camera, and the model estimating that some of the joints that are not visible within the image might be behind the camera. But this is unlikely to happen.
