### ISSUE TITLE
Errors in dataset_preparation

### ISSUE THREAD

**Issue by Eunho-J** [isarandi/metrabs#39]
I think you need to remove if-state in run_yolo.sh to your README.md's code run (in your darknet repository)

```
if [[ -f $IMG_PATHS_FILE ]]; then
    image_paths=$(cat "$IMG_PATHS_FILE")
else
    image_paths=$(find "$IMG_ROOT" -name '*.jpg')
fi
```

to

```
image_paths=$(find "$IMG_ROOT" -name '*.jpg')
```

**Comment by Eunho-J** [comment]
or add code checking for unbound

**Comment by Eunho-J** [comment]
Oh and also in your metrabs,
dataset_preparation/all.sh should be modified as below

```
darknet/run_yolo.sh --image-root "$DATA_ROOT/mpii" --out-path "$DATA_ROOT/mpii/yolov3_detections.pkl"
```

to

```
darknet/run_yolo.sh --image-root "$DATA_ROOT/mpii" --out-path "$DATA_ROOT/mpii/yolov3_detections.pkl" --jobs 3
```

(3 or other number)

it's similar problem with above

**Comment by Eunho-J** [comment]
in dataset_preparation/get_3dhp.sh 
```
sed -i 's/subjects=(1 2)/subjects=(1 2 3 4 5 6 7 8)/' conf.ig
sed -i "s/destination='.\/'/'destination=$DATA_ROOT\/3dhp\/'/" conf.ig
sed -i "s/ready_to_download=0/ready_to_download=1/" conf.ig
bash get_dataset.sh
```
make error
"unrecognized option for `s'"

```
sed -i 's/subjects=(1 2)/subjects=(1 2 3 4 5 6 7 8)/' conf.ig
sed -i 's/destination=".\/"/destination="$DATA_ROOT\/3dhp\/"/' conf.ig
sed -i 's/ready_to_download=0/ready_to_download=1/' conf.ig
bash get_dataset.sh
```
worked for me

**Comment by Eunho-J** [comment]
and for darknet, as 'make' fails with error "CUDNN_CONVOLUTION_FWD_SPECIFY_WORKSPACE_LIMIT" undefined,

I used https://github.com/pjreddie/darknet and added your run_yolo.sh and modified it.

**Comment by Eunho-J** [comment]
oh i also found that unbound errer can be fixed with erasing 'u' option in run_yolo.sh.

**Comment by isarandi** [comment]
Thanks! I added another check in run_yolo.sh whether $IMG_PATHS_FILE is supplied or not.
However, I now mostly use the TensorFlow-based YOLOv4 from https://github.com/isarandi/tensorflow-yolov4-tflite
