### ISSUE TITLE
Would you please explain the training details about 3DPW challenges?

### ISSUE THREAD

**Issue by gsygsygsy123** [isarandi/metrabs#4]
Hi @isarandi, congratulations on winning the 3DPW challenge!
I have great interst to your work. But I found some detals, like upper body crop, are missed. I want to know what extactly upper body crop means? Crop body upper the left/right hips?  If so, I wonder why only crop the upper body? why not crop the lower body or randomly crop the body?

**Comment by isarandi** [comment]
Hi @gsygsygsy123,

In natural environments, it's much more frequent to see only someone's upper body (e.g. standing behind a desk or other object), compared to only seeing the legs but not the upper body. It simply means an augmentation where the crop bounding box is adjusted to exclude the leg joints (knees and ankles). It actually does not make a huge difference on 3DPW, it was just one of the things I added for stronger augmentation. It would require further analysis to establish if it really is important to use.

**Comment by gsygsygsy123** [comment]
I see, thanks for your thoughtful answer!
