### ISSUE TITLE
get smpl pose

### ISSUE THREAD

**Issue by luoww1992** [isarandi/metrabs#44]
i have run it ,  the results are 3d keypoints and human box ?and i notice the smpl in the code ,
so,
Q1: i want to get the smpl pose for the results , how to do ? i find the result show likes smpl in project with visualize 
I'm checking the project code ,
and can you give me some advices or some python module to get it ?

**Comment by isarandi** [comment]
Hi, thanks for your interest! This project only estimates 3D keypoint locations for various reasons (training data availability, simpler formulation). To get SMPL parameters, one may perform inverse kinematics from the joint locations or more fundamentally change the network and retrain on appropriate data.
