### ISSUE TITLE
the dataset used in demo video?

### ISSUE THREAD

**Issue by 1165048017** [isarandi/metrabs#46]
I have noticed that in demo video, there are eyes/ears 3D keypoints
<img width="337" alt="image" src="https://user-images.githubusercontent.com/15133787/191405594-5259d535-a098-4219-815a-8d2f33dff905.png">
But , the datasets in  `dataset_preparation`, 3D joints have no additonal keypoints named eyes/ears~~~
Could you please tell me which dataset is used in demo video~~~~
Thank you very much ^_^

**Comment by isarandi** [comment]
The eyes and ears come from the CMU-Panoptic dataset (and weak 2D supervision from COCO). CMU-Panoptic preprocessing code is not yet included in the repo, but I'm planning to add it soon, along with several others. Currently only those datasets are used in the public repo that were used in the published paper.

**Comment by Gmaldonad17** [comment]
Hello! I read your paper it is a great work. For a project I need to train metrabs on the CMU Panoptic dataset, I was wondering if  you could share the pre-processing code for cmu panoptic.
