### ISSUE TITLE
About “many” dataset and “roundrobin_sizes“ 

### ISSUE THREAD

**Issue by rootpine** [isarandi/metrabs#47]
Hi, thank you for sharing this great project.

I would like to compare the performance of my trained model with your models uploaded in [MODELS.md](https://github.com/isarandi/metrabs/blob/master/docs/MODELS.md). So,

Q1. How many examples (cropped single persons) from each dataset are included in your "many” training dataset (Human3.6m+MuCo-3DHP+CMU-Panoptic+SAIL-VOS+SURREAL+AIST-Dance++)? I would like to know the composition of the number of examples.

Q2. What is the set value of “roundrobin_sizes“ when training your Metrabs models on the “many” dataset? Is it the same as the value set [here (main.py)](https://github.com/isarandi/metrabs/blob/c43a57abe2eb745625f87ff8efeae1bcd23ffade/src/main.py#L46) ?

**Comment by isarandi** [comment]
Hi, thanks for your interest!

There is a major update coming soon with even more datasets and better results (with the corresponding paper currently under review). So perhaps it would make sense to wait a bit for those.

Is your comparison planned for a publication?

**Comment by rootpine** [comment]
Thank you for your prompt reply.
That’s great, I look forward to your next paper!!

“Is your comparison planned for a publication?”
> Not for now. I’m new to this direction and studying previous studies.
(Actually I have prepared own “many” dataset and successfully trained a Metrabs model, but the result was little worse than yours. If it is okay with you, please share me more about the composition of your “many” dataset for the current repository.)

**Comment by isarandi** [comment]
The number of individual examples per each dataset (after my preprocessing) is approximately:

- Human3.6M: 165k
- MuCo-3DHP: 677k
- CMU-Panoptic: 2.8M
- SAIL-VOS: 101k
- SURREAL: 1.9M
- AIST-Dance++: 1.9M

The roundrobin sizes (i.e. the batch composition) for the currently uploaded models was simply 16 examples from each of the six datasets, so 96 3D labeled examples in total, plus 32 COCO examples with 2D labels (for weak supervision).

**Comment by rootpine** [comment]
Thank you for your kind reply …!!
