### ISSUE TITLE
InvalidArgumentError: Invalid PNG data, size 706833 [Op:DecodeJpeg]

### ISSUE THREAD

**Issue by justintiger** [isarandi/metrabs#5]
Hi Thank for this model,

I wanted to test this model with my own pic. But i got a problem while i called the YOLO model to get 2D-Keypoints, Can u help?
Background: I transfer a depth maps to fake-rgb pictures and want to try the accuracy.  Can u give me some suggestions?

**Comment by isarandi** [comment]
Looks like you are trying to decode a PNG file (instead of a JPEG file) using the `decode_jpeg` function.
