### ISSUE TITLE
how to get point position from poseviz space

### ISSUE THREAD

**Issue by luoww1992** [isarandi/metrabs#50]
i notice that intrinsic_matrix: a float32 Tensor of shape [3, 3], the camera's intrinsic matrix. If left at the default value, the intrinsic matrix is determined from the default_fov_degrees argument in API.md.
when i run https://github.com/isarandi/metrabs/blob/master/demo_video_batched.py with default args in model.detect_poses_batched(),.
so,
Q1: there is no intrinsic_matrix args,  the result pred['poses3d'] is the 3d position in the camera coordinate, not the 3D world coordinate system ?
Q2: show the result poses3d in poseviz space, and i see the camera = poseviz.Camera.from_fov(55, frame_batch.shape[1:3]) and  use the default args default_fov_degrees=55,  
how to get the points world 3d position by fov_degress=55 in poseviz space

**Comment by isarandi** [comment]
> Q1: there is no intrinsic_matrix args, the result pred['poses3d'] is the 3d position in the camera coordinate, not the 3D world coordinate system ?

The transformation between world and camera space is determined by the extrinsic parameters. The intrinsic parameters are needed when transforming from the camera space to the image space.

So if `extrinsic_matrix` is not supplied, the prediction is in camera space.

If `intrinsic_matrix` is not supplied, then by default a field of view of 55 degrees is assumed and the principal point is assumed to be at the image center.

I answered some related questions at https://github.com/isarandi/metrabs/issues/52

**Comment by smoonroblox** [comment]
> > Q1: there is no intrinsic_matrix args, the result pred['poses3d'] is the 3d position in the camera coordinate, not the 3D world coordinate system ?
> 
> The transformation between world and camera space is determined by the extrinsic parameters. The intrinsic parameters are needed when transforming from the camera space to the image space.
> 
> So if `extrinsic_matrix` is not supplied, the prediction is in camera space.
> 
> If `intrinsic_matrix` is not supplied, then by default a field of view of 55 degrees is assumed and the principal point is assumed to be at the image center.
> 
> I answered some related questions at #52

@isarandi   This also applies for Metro? I don't need to set the field of view for prediction?

**Comment by luoww1992** [comment]
now a plan B? -- split the savedModel.
----- 原始邮件 -----
发件人：István Sárándi ***@***.***>
收件人：isarandi/metrabs ***@***.***>
抄送人：luoww1992 ***@***.***>,  Author ***@***.***>
主题：Re: [isarandi/metrabs] how to get point position from poseviz space (Issue #50)
日期：2023年06月14日 15点05分


MeTRo does not need the field of view or focal length, but it only provides a root-relative 3D prediction, which can't be projected to image pixels. It's an earlier form of the model, which doesn't get exposed through a high level, easy to use SavedModel like MeTRAbs is.

&mdash;
