### ISSUE TITLE
[Error] URL fetch failure

### ISSUE THREAD

**Issue by moonsh** [isarandi/metrabs#57]
There is a problem with building a backbone during training.

Exception: URL fetch failure on https://storage.googleapis.com/keras-applications/resnet/resnet50v2_weights_tf_dim_ordering_tf_kernels_notop.h5: 403 -- Forbidden

Could you check?

**Comment by moonsh** [comment]
solved problem

**Comment by isarandi** [comment]
Seems like that link is still broken. How did you solve it?

**Comment by moonsh** [comment]
Change link to this   https://storage.googleapis.com/tensorflow/keras-applications/resnet/
