### ISSUE TITLE
Mixing 2d keypoints

### ISSUE THREAD

**Issue by cohyun** [isarandi/metrabs#59]
Hi. Thanks for your nice project. 
I'm learning many things from your project everyday.

I want to know if I can detect 3d pose giving 2d pose as input (not an image as input). For example, I need humaneva15 skeleton and I think that skeleton can be made by mixing  LHip from 2d smpl_24 pose and Head from 2d mpi_inf_3dhp_28 pose and etc.. After that, I wish I could put that 2d keypoints as input and lift them to 3d pose. 

So can you tell me is there anyway to put 2d pose as input and get 3d pose as output by your code? 

Thanks for reading :)

**Comment by isarandi** [comment]
Hello, no this work does not perform 2D-to-3D lifting, so you can't input 2D keypoints.
