### ISSUE TITLE
install the dependencies 404 error

### ISSUE THREAD

**Issue by ryo-matsuzaka** [isarandi/metrabs#6]
Hi.
Thank you very much for sharing great work!
I cannot access to [install the dependencies](https://github.com/isarandi/metrabs/blob/master/DEPENDENCIES.md) at [README](https://github.com/isarandi/metrabs/blob/master/README.md).
Could you fix it?

**Comment by ryo-matsuzaka** [comment]
Also [demo.py](https://github.com/isarandi/metrabs/blob/master/src/demo.py)
Excuse me for minor comments.

**Comment by isarandi** [comment]
Thank you for letting me know, I fixed the links. I just noticed that in a reorganization I removed the .md file for installing dependencies and rather wrote it as a .sh Bash script with comments.
