### ISSUE TITLE
Question about joint-transform-file 

### ISSUE THREAD

**Issue by kimx3966** [isarandi/metrabs#62]
It's a great work! I have a question about joint-transform-file. Where can I find the file? Could you provide it for us?

**Comment by isarandi** [comment]
Actually, its only functionality at the moment is to produce also KinectV2-like joints. It's 555x580, though the beginning is simply the identity matrix and the rest of the matrix specifies how to linearly combine the 555 to get the 25 Kinect joints.

Here is the file: [joint_transform.zip](https://github.com/isarandi/metrabs/files/12373368/joint_transform.zip)
