### ISSUE TITLE
Can't install cameralib

### ISSUE THREAD

**Issue by matbord** [isarandi/metrabs#64]
I have run install_dependencies.sh, now I'm trying to run code in demos folder and everytime I have to import cameralib I get the following error
```
import cameralib
ModuleNotFoundError: No module named 'cameralib'
```

How can I install cameralib?

**Comment by isarandi** [comment]
Thanks for your interest! `pip install git+https://github.com/isarandi/cameralib.git` should work, but it's included in `environment.yml` already. Alternatively `conda install cameralib -c isarandi`, but Conda packaging is a bit more finicky so it may work better with pip.
