### ISSUE TITLE
Calculation of AUC

### ISSUE THREAD

**Issue by kuang23** [isarandi/metrabs#65]
Hi,

How do 31 and 100 come from in get_auc() of eval_3dhp.py?
Is the result of this get_auc() same as “The AUC is the area under the PCK curve as the threshold ranges from 0 to 150mm” in the paper?

**Comment by isarandi** [comment]
Yes, it is that metric. However in order to ensure perfectly matching the original Matlab evaluation code, a discretization needs to be emulated like this. I discuss these issues in Sections 3.4.4 and 3.4.7 in my PhD thesis: https://istvansarandi.com/media/sarandi_phd_thesis_draft.pdf
