### ISSUE TITLE
question about the paper

### ISSUE THREAD

**Issue by dx118** [isarandi/metrabs#66]
Hi, thank you for the excellent work. I have one question after reading the WACV 2023 paper.

Though different skeletons have different topologies, they often share similar end-effector definition(say hand and foot), so have you tested supervising all the skeleton's end-effector position with same ground truth while left other joints to work with the proposed autoencoder? 

This is just a shallow thought on my part, could there be something wrong with it?

**Comment by isarandi** [comment]
Thank you for your interest and question. The main benefit of our method is that we don't need to think about such heuristics or special cases. Just put all joints in a big pot and the rest is taken care of, the algorithm finds out how those joints are related without specifying that wrists or ankles are always the same. Also, it's not entirely true that the ankle points are always defined the same way in all datasets.

So overall I have not tried such a thing, and it may be possible to squeeze some extra performance by hand-coding some special cases.

**Comment by dx118** [comment]
Fine, Thank you for your kind reply.
