### ISSUE TITLE
could not find ffmpeg after search through Python error

### ISSUE THREAD

**Issue by matbord** [isarandi/metrabs#67]
Hello, I run install_dependencies and then activated the metralab environment. I run the demo_video.py with my video and I get the following error regarding ffmpeg
![image](https://github.com/isarandi/metrabs/assets/45484331/7c4a2f8b-bd5a-4a04-9ddc-b524d29c981f)
Do you know how I can solve it?

**Comment by isarandi** [comment]
It looks like Tensorflow's FFMPEG wrapper is not present and some issues also with libavcodec, indicating an issue with some combination of tensorflow-io, ffmpeg and libavcodec.
On Ubuntu, you could try `sudo apt install libavcodec-extra libavformat-dev ffmpeg`.

**Comment by rmknan** [comment]
@matbord I am facing the same issue and I tried the above method but it did not work. Were you able to solve it?

**Comment by matbord** [comment]
@rmknan No, I wasn't able to solve it so I changed library

**Comment by isarandi** [comment]
You don't have to use tensorflow's ffmpeg. You can also just load the images yourself, e.g. using imageio-ffmpeg. This issue is independent of this repository.

**Comment by rmknan** [comment]
Thanks for the reply! It was a TensorFlow dependency issue.
