### ISSUE TITLE
Possible ways to speed up ?

### ISSUE THREAD

**Issue by pramishp** [isarandi/metrabs#8]
I ran this in google colab, the results were really great.  It took about 16s for inference with the box provided. I was wondering if there are ways to speed this up significantly for single person pose estimation even for CPU optimized inference.

**Comment by zhLawliet** [comment]
i run the "python -m scripts.video_inference --gt-assoc --dataset=3dpw **",   It took about 3h for one sequenceFile, it is too slow, maybe there are some error about my operate.
![image](https://user-images.githubusercontent.com/17424385/133562847-d071da6f-6429-4e4b-a2fb-81c71cca26e8.png)

and i find the tf.config.experimental.list_physical_devices('GPU') is [],   however  have  four  Tesla P40 on my computer.
