### ISSUE TITLE
What Method was used to get the skeleton format of SMPL?

### ISSUE THREAD

**Issue by Rakesh-Paul01** [isarandi/metrabs#80]
Hi This is a amazing work done by you

I am trying to figure out what method you used to get the pose estimation in the SMPL format (they have foot and multiple spines). In case it was some dataset on which it was trained could you mention which dataset was used?

thank you

**Comment by isarandi** [comment]
Yes, SURREAL, AGORA, BEHAVE and perhaps more I'm forgetting. You can check in the paper. By the way, something much better is in the making so stay tuned :)

**Comment by Rakesh-Paul01** [comment]
@isarandi Thanks for the response. These datasets aren't only of video to 3D mesh cloud? I was under the impression that they gave only mesh cloud points and not the skeleton(like the ones that you have for the smpl one). Cause most papers that used this dataset used the mesh and not the 3D skeleton.

Can you confirm what I assume is correct? (I don't have access to these datasets at the moment hence can't verify myself)

also eagerly waiting for the new and exiting stuff you bring.

**Comment by isarandi** [comment]
SMPL contains both surface mesh vertices and body-internal joint positions.

**Comment by Rakesh-Paul01** [comment]
So in order to get the 3D kinematic skeleton I have to map the smpl mesh on the video and it should output me the body-internal joint positions is that right what I infer? Also does it output the rotational parameters as well?

**Comment by isarandi** [comment]
MeTRAbs itself does not estimate rotations. It estimates point locations. I'm not sure if your question relates to understanding this estimator or how SMPL itself works. Overall, note that this MeTRAbs model is not tailored to SMPL, all it can do is estimate joint locations in various formats depending on the training data, one of which is the SMPL joint convention. What you do with those joint locations is up to you.

**Comment by Rakesh-Paul01** [comment]
Yeah sorry, I started asking about the rotations and the questions became related more towards SMPL rather than metrabs. Ig you have answered the original question so I am closing the issue.
