### ISSUE TITLE
Correspondence relation between the elements of np_3d_pose and body parts

### ISSUE THREAD

**Issue by ryo-matsuzaka** [isarandi/metrabs#9]
Hello, Mr.Sarandi.
Thank you for sharing your state of the art achievement!
I want to ask about correspondence relation between the elements of `np_3d_pose `and body parts(head, right hand, ...).
Could you tell me the clue to identify it? I want to calculate the angle of body part.

**Comment by isarandi** [comment]
Hello, you can take a look here for how to get the joint names as strings: https://github.com/isarandi/metrabs/blob/1aa1e756d84c541353b19fcf64fb49bf38c1f09e/src/scripts/video_inference.py#L49

**Comment by ryo-matsuzaka** [comment]
Thank you so much!

**Comment by ryo-matsuzaka** [comment]
I tried with `singleperson_smpl`, `multiperson_smpl`, and `multiperson_smpl_combined`.
And I can get the name of joints for `multiperson_smpl`.

For the other models, I got 

> AttributeError: '_UserObject' object has no attribute 'joint_names'

But anyway, I could solve the issue. Thank you!
